### PR TITLE
Bump tensorflow version: 1.13.1 -> 1.14.0

### PR DESCRIPTION
**Pull request by rculbertson**

### CODE REVIEW

**Comment by brianmartin** [comment]
Hey @rculbertson, mind providing some description of the `pandas` pinning? It's definitely a bit of a smell.

**Comment by rculbertson** [comment]
@brianmartin The build had been failing with this error
```
AttributeError: module 'pandas' has no attribute 'core'
```
So I was changing the pandas version, as some Stackoverflow posts suggested. But now it seems to be working, so I removed that change.

**Comment by daikeshi** [comment]
We use tfx 0.13, it might not be fully compatible with tf 1.14 based on this table https://github.com/tensorflow/tfx#compatible-versions. Shall we wait for tfx 0.14 release? I think it will be out soon.

**Comment by rculbertson** [comment]
@daikeshi Someone is trying to move to python 3, and apparently needs the latest version of tensorflow to do that (see #210). They may be able to workaround this for now though. I'll follow up.

**Comment by konsoz** [comment]
tfx 0.14 is released:
https://github.com/tensorflow/tfx#compatible-versions

Can we merge this one now?

**Comment by konsoz** [comment]
#215 Can be merged after?

**Comment by konsoz** [comment]
Ah, they only released rc0, let's wait to get 0.14.0 fully released

**Pull request merged**
