### PR TITLE
add code to generate tf test resources

### PR DESCRIPTION
**Pull request by yonromai**
Before this PR, one had to copy the tfrecords used for integration testing. 
This PR adds the code needed to generate the tfrecords used for testing.

### CODE REVIEW

**Comment by yonromai** [comment]
@richwhitjr

**Comment by richwhitjr** [comment]
LGTM

**Comment by yonromai** [comment]
@richwhitjr would you mind installing the pip package from this branch and checking that it fixes your issue?

**Comment by richwhitjr** [comment]
Ran on an internal dataset and results match what I would expect now.

**Pull request merged**
